# Generated by Django 6.0.3 on 2026-04-05 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='告警名称')),
                ('type', models.CharField(choices=[('email', '邮箱告警')], default='email', max_length=20, verbose_name='告警类型')),
                ('config', models.JSONField(default=dict, verbose_name='告警配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警方式',
                'verbose_name_plural': '告警方式',
                'db_table': 'alert_method',
            },
        ),
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='模板名称')),
                ('title', models.CharField(max_length=256, verbose_name='告警标题')),
                ('content', models.TextField(verbose_name='告警内容模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警模板',
                'verbose_name_plural': '告警模板',
                'db_table': 'alert_template',
            },
        ),
        migrations.CreateModel(
            name='ProbeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('target_type', models.CharField(choices=[('host', '主机'), ('port', '端口')], max_length=10, verbose_name='目标类型')),
                ('target', models.CharField(max_length=256, verbose_name='目标 IP/IP:端口')),
                ('detect_interval', models.IntegerField(default=60, verbose_name='探测间隔(秒)')),
                ('fail_threshold', models.IntegerField(default=3, verbose_name='连续失败次数告警')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_status', models.CharField(blank=True, choices=[('up', '正常'), ('down', '异常')], max_length=10, null=True, verbose_name='最后状态')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='最后探测时间')),
                ('consecutive_fail', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alert.alertmethod', verbose_name='告警方式')),
                ('alert_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alert.alerttemplate', verbose_name='告警模板')),
            ],
            options={
                'verbose_name': '探针规则',
                'verbose_name_plural': '探针规则',
                'db_table': 'probe_rule',
            },
        ),
        migrations.CreateModel(
            name='ProbeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', '正常'), ('down', '异常')], max_length=10, verbose_name='状态')),
                ('latency', models.FloatField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('message', models.TextField(default='', verbose_name='消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='alert.proberule', verbose_name='探针规则')),
            ],
            options={
                'verbose_name': '探测日志',
                'verbose_name_plural': '探测日志',
                'db_table': 'probe_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
