# Generated by Django 6.0.3 on 2026-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmethod',
            name='alert_interval',
            field=models.IntegerField(default=3600, help_text='两次告警之间的最小间隔时间', verbose_name='告警间隔(秒)'),
        ),
        migrations.AddField(
            model_name='proberule',
            name='last_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次告警发送时间'),
        ),
    ]
