# Generated by Django 6.0.3 on 2026-04-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alertmethod_alert_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.qq.com', max_length=128, verbose_name='SMTP服务器')),
                ('smtp_port', models.IntegerField(default=465, verbose_name='SMTP端口')),
                ('smtp_username', models.CharField(blank=True, max_length=128, null=True, verbose_name='SMTP用户名')),
                ('smtp_password', models.CharField(blank=True, max_length=256, null=True, verbose_name='SMTP密码')),
                ('smtp_ssl', models.BooleanField(default=True, verbose_name='启用SSL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局SMTP配置',
                'verbose_name_plural': '全局SMTP配置',
                'db_table': 'global_smtp_config',
            },
        ),
        migrations.RemoveField(
            model_name='alertmethod',
            name='config',
        ),
        migrations.AddField(
            model_name='alertmethod',
            name='to_list',
            field=models.JSONField(default=list, help_text='邮箱地址列表', verbose_name='收件人列表'),
        ),
        migrations.AlterField(
            model_name='alertmethod',
            name='alert_interval',
            field=models.IntegerField(default=300, help_text='两次告警之间的最小间隔时间', verbose_name='告警间隔(秒)'),
        ),
    ]
