# Generated by Django 6.0.3 on 2026-04-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_globalsmtpconfig_remove_alertmethod_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proberule',
            name='alert_interval',
            field=models.IntegerField(default=300, help_text='两次告警之间的最小间隔时间', verbose_name='告警间隔(秒)'),
        ),
    ]
