# Generated by Django 6.0.3 on 2026-04-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_proberule_alert_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertmethod',
            name='alert_interval',
        ),
        migrations.RemoveField(
            model_name='alertmethod',
            name='is_active',
        ),
    ]
