"""
Django settings for BackEnd project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-de3_&o&sk*ij&7cwnz0@e_^e!$i143oodn8!l%u1alg#nkw8fv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'www.wacgee.icu',
    '106.13.85.137',
    'localhost'
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django_filters',
    #'django.contrib.sessions',
    #'django.contrib.messages',
    #'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'django_redis',
    'rbac',
    'perm',
    'audit',
    'terminal',
    'resource'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    #'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    #'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'perm.authentication.TokenAuthorization',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'perm.authentication.TokenPermission',  # 建议同时设置全局权限
    ],
    # 核心：只保留JSON渲染器，彻底禁用HTML调试界面
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # 可选：全局指定默认Content-Type
    'DEFAULT_CONTENT_TYPE': 'application/json',
}

# 允许所有 域名/IP 跨域
CORS_ALLOW_ALL_ORIGINS = True
# 配置可跨域访问的 域名/IP
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8080',
    'https://www.wacgee.icu',
]
# 使用正则表达式匹配允许访问的 域名/IP
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://\w+\.example\.com$",
]

# 配置允许的请求方式
CORS_ALLOW_METHODS = [
    '*', # * 表示允许全部请求头
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'BackEnd.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates']
#         ,
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             #"PASSWORD": "your_password",  # 如果有密码
#             "SOCKET_CONNECT_TIMEOUT": 5,  # 连接超时
#             "SOCKET_TIMEOUT": 5,          # 读写超时
#             "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
#             "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
#             "CONNECTION_POOL_KWARGS": {
#                 "max_connections": 100,
#                 "retry_on_timeout": True,
#             }
#         },
#         "KEY_PREFIX": "myproject",  # 缓存键前缀
#     }
# }



WSGI_APPLICATION = 'BackEnd.wsgi.application'
ASGI_APPLICATION = 'BackEnd.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        #'NAME': 'E:/sqlite/db.sqlite3',
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'ptp',      # 数据库名
    #     'USER': 'root',           # 用户名
    #     'PASSWORD': '936949426',       # 密码
    #     'HOST': '127.0.0.1',               # 主机
    #     'PORT': '3306',                    # 端口
    #     'OPTIONS': {
    #         'charset': 'utf8mb4',
    #     },
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 简体中文
USE_I18N = True
USE_L10N = True

TIME_ZONE = 'Asia/Shanghai'#'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
#minutes=15
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=200),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'  # 或 smtp.163.com, smtp.gmail.com
EMAIL_PORT = 587  # 或 465 (SSL)
EMAIL_USE_TLS = True  # 如果端口是587
EMAIL_USE_SSL = False  # 如果端口是465
EMAIL_HOST_USER = '1964282264@qq.com'  # 发件邮箱
EMAIL_HOST_PASSWORD = 'fxbxrnuxhilbdjdc'  # 邮箱授权码，不是密码
DEFAULT_FROM_EMAIL = '1964282264@qq.com'  # 默认发件人

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],  # Redis 地址
#         },
#     },
# }