# Generated by Django 5.2.2 on 2026-01-10 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resource.resourcegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('publiced', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_resource_accounts', to='rbac.user')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', unique=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('port', models.IntegerField(default=22)),
                ('is_production', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.user')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resource.protocol')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resource.resourcegroup')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resource.resourcetype')),
                ('vouchers', models.ManyToManyField(blank=True, related_name='resources', to='resource.resourcevoucher')),
            ],
        ),
        migrations.AddConstraint(
            model_name='resourcevoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('password__isnull', False), ('private_key__isnull', True)), models.Q(('password__isnull', True), ('private_key__isnull', False)), _connector='OR'), name='resourcevoucher_exactly_one_of_password_or_private_key'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ipv4_address__isnull', False), ('ipv6_address__isnull', True)), models.Q(('ipv4_address__isnull', True), ('ipv6_address__isnull', False)), _connector='OR'), name='resource_exactly_one_ip'),
        ),
    ]
