# Generated by Django 5.2.2 on 2026-01-28 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'protocol',
            },
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('protected', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resource.resourcegroup')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaf', to='resource.resourcegroup')),
            ],
            options={
                'db_table': 'resource_group',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ssh_vouchers', to='resource.resourcegroup')),
            ],
            options={
                'db_table': 'voucher',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', unique=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('port', models.IntegerField(default=22)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resource.protocol')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resources', to='resource.resourcegroup')),
                ('vouchers', models.ManyToManyField(blank=True, related_name='resources', to='resource.voucher')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('password__isnull', False), ('private_key__isnull', True)), models.Q(('password__isnull', True), ('private_key__isnull', False)), _connector='OR'), name='voucher_exactly_one_of_password_or_private_key'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ipv4_address__isnull', False), ('ipv6_address__isnull', True)), models.Q(('ipv4_address__isnull', True), ('ipv6_address__isnull', False)), _connector='OR'), name='resource_exactly_one_ip'),
        ),
    ]
