# Generated by Django 6.0 on 2026-01-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourcevoucher',
            name='resourcevoucher_exactly_one_of_password_or_private_key',
        ),
        migrations.AddConstraint(
            model_name='resourcevoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('password__isnull', False), ('private_key__isnull', True)), models.Q(('password__isnull', True), ('private_key__isnull', False)), _connector='OR'), name='resourcevoucher_exactly_one_of_password_or_private_key'),
        ),
    ]
