# Generated by Django 6.0.3 on 2026-03-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='protocols',
        ),
        migrations.AddField(
            model_name='resource',
            name='protocol',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resources', to='resource.protocol'),
        ),
    ]
