# Generated by Django 5.2.2 on 2026-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='protocol',
        ),
        migrations.AddField(
            model_name='resource',
            name='protocols',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resource.protocol'),
        ),
    ]
