# Generated by Django 6.0.3 on 2026-03-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_change_protocol_to_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='status',
        ),
    ]
