# Generated by Django 6.0 on 2026-01-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('resource', '0002_remove_resourcevoucher_resourcevoucher_exactly_one_of_password_or_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='resource_exactly_one_ip',
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ipv4_address__isnull', False), ('ipv6_address__isnull', True)), models.Q(('ipv4_address__isnull', True), ('ipv6_address__isnull', False)), _connector='OR'), name='resource_exactly_one_ip'),
        ),
    ]
