# Generated by Django 6.0.3 on 2026-03-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_remove_resource_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHBlacklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern', models.CharField(help_text='正则表达式模式', max_length=255)),
                ('description', models.TextField(blank=True, help_text='规则描述', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_blacklists', to='resource.resourcegroup')),
            ],
            options={
                'db_table': 'ssh_blacklist',
            },
        ),
    ]
