# Generated by Django 6.0.3 on 2026-03-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_sshblacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSHBlacklist',
        ),
    ]
