# Generated by Django 6.0.3 on 2026-03-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0005_delete_sshblacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHCommandFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern', models.CharField(help_text='命令模式', max_length=255)),
                ('type', models.CharField(choices=[('exact', '精确匹配'), ('prefix', '前缀匹配'), ('regex', '正则匹配')], default='exact', help_text='匹配类型', max_length=10)),
                ('priority', models.IntegerField(default=0, help_text='优先级（数值越大优先级越高）')),
                ('description', models.TextField(blank=True, help_text='规则描述', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_command_filters', to='resource.resourcegroup')),
            ],
            options={
                'db_table': 'ssh_command_filter',
            },
        ),
        migrations.CreateModel(
            name='ResourceGroupCommandMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('blacklist', '黑名单模式')], default='blacklist', help_text='过滤模式', max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_mode', to='resource.resourcegroup')),
            ],
            options={
                'db_table': 'resource_group_command_mode',
                'unique_together': {('group',)},
            },
        ),
    ]
