# Generated by Django 6.0.3 on 2026-04-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_blacklist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceGroupCommandMode',
        ),
    ]
