# Generated by Django 6.0.3 on 2026-04-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_delete_sshblacklist'),
        ('ssh_blacklist', '0002_delete_resourcegroupcommandmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHBlacklistRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, verbose_name='匹配模式')),
                ('type', models.CharField(choices=[('exact', '精确匹配'), ('prefix', '前缀匹配'), ('regex', '正则匹配')], default='exact', max_length=20, verbose_name='匹配类型')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_blacklist_rules', to='resource.resourcegroup', verbose_name='系统组')),
            ],
            options={
                'verbose_name': 'SSH黑名单规则',
                'verbose_name_plural': 'SSH黑名单规则',
                'db_table': 'ssh_blacklist_rule',
            },
        ),
        migrations.DeleteModel(
            name='SSHCommandFilter',
        ),
    ]
