# Generated by Django 6.0.3 on 2026-03-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelloperationlog',
            name='block_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shelloperationlog',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shelloperationlog',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
