# Generated by Django 6.0 on 2026-01-01 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='voucher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='resource.resourcevoucher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
