# Generated by Django 5.2.2 on 2026-01-10 09:37

import django.db.models.deletion
import rbac.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=15)),
                ('object', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20, unique=True, verbose_name='账户')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='邮箱')),
                ('status', models.BooleanField(default=True, verbose_name='是否是正常用户')),
                ('protected', models.BooleanField(default=False, verbose_name='保护标志位')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='电话')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=rbac.models.avatar_upload_path, verbose_name='头像')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('login_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('protected', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('perms', models.ManyToManyField(related_name='roles', through='perm.BaseAuth', to='rbac.permission')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_roles', to='rbac.user')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_roles', to='rbac.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_groups', to='rbac.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rbac.usergroup')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_groups', to='rbac.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(related_name='users', to='rbac.usergroup'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='rbac.UserRole', to='rbac.role'),
        ),
    ]
