# Generated by Django 5.2.2 on 2026-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('component', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('permission_code', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
