# Generated by Django 6.0.3 on 2026-04-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='连接名称')),
                ('host', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.TextField(verbose_name='密码(加密存储)')),
                ('database', models.CharField(blank=True, default='', max_length=100, verbose_name='默认数据库')),
                ('charset', models.CharField(default='utf8mb4', max_length=50, verbose_name='字符集')),
                ('connection_timeout', models.IntegerField(default=5, verbose_name='连接超时(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysql_connections', to='rbac.user', verbose_name='创建者')),
            ],
            options={
                'db_table': 'mysql_connection',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='MysqlAuditLogV2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('SELECT', '查询'), ('INSERT', '插入'), ('UPDATE', '更新'), ('DELETE', '删除'), ('ALTER', '结构变更'), ('DROP', '删除对象'), ('TRUNCATE', '清空表'), ('CREATE', '创建对象'), ('LOGIN', '登录连接'), ('LOGOUT', '断开连接'), ('ROLLBACK', '回滚操作')], max_length=20, verbose_name='操作类型')),
                ('sql_statement', models.TextField(blank=True, null=True, verbose_name='SQL语句')),
                ('table_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='目标表名')),
                ('affected_rows', models.IntegerField(default=0, verbose_name='影响行数')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='变更前数据')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='变更后数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='会话ID')),
                ('risk_level', models.CharField(choices=[('LOW', '低风险'), ('MEDIUM', '中风险'), ('HIGH', '高风险'), ('CRITICAL', '严重风险')], default='LOW', max_length=20, verbose_name='风险等级')),
                ('is_rollback', models.BooleanField(default=False, verbose_name='是否回滚')),
                ('approval_status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('AUTO_APPROVED', '自动通过')], default='AUTO_APPROVED', max_length=20, verbose_name='审批状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mysql_audit_logs', to='rbac.user', verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysql_audit_logs', to='rbac.user', verbose_name='操作用户')),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='mysql_manager.mysqlconnection', verbose_name='连接')),
            ],
            options={
                'db_table': 'mysql_audit_log_v2',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['connection', '-created_at'], name='mysql_audit_connect_31f506_idx'), models.Index(fields=['user', '-created_at'], name='mysql_audit_user_id_8641d3_idx'), models.Index(fields=['risk_level', '-created_at'], name='mysql_audit_risk_le_b3b06c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MysqlQueryHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sql_text', models.TextField(verbose_name='SQL语句')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行耗时(ms)')),
                ('rows_affected', models.IntegerField(default=0, verbose_name='影响行数')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('ERROR', '失败'), ('TIMEOUT', '超时')], default='SUCCESS', max_length=20, verbose_name='执行状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to='mysql_manager.mysqlconnection', verbose_name='连接')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysql_queries', to='rbac.user', verbose_name='操作用户')),
            ],
            options={
                'db_table': 'mysql_query_history',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['connection', '-executed_at'], name='mysql_query_connect_a611a5_idx'), models.Index(fields=['user', '-executed_at'], name='mysql_query_user_id_3a86f7_idx')],
            },
        ),
    ]
