# Generated by Django 5.2.2 on 2026-01-28 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perm', '0001_initial'),
        ('rbac', '0001_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseauth',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_authorizations', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='baseauth',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_authorizations', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='resourcegroupauth',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_group_authorizations', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='resourcegroupauth',
            name='resource_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_group_authorizations', to='resource.resourcegroup'),
        ),
        migrations.AddField(
            model_name='resourcegroupauth',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_group_authorizations', to='rbac.role'),
        ),
    ]
