# Generated by Django 5.2.2 on 2026-01-10 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perm', '0001_initial'),
        ('rbac', '0001_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseauth',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_authorizations', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='baseauth',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_authorizations', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='resourceauth',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='resourceauth',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_authorizations', to='resource.resource'),
        ),
        migrations.AddField(
            model_name='resourceauth',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='resourceauth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rbac.user'),
        ),
        migrations.AddField(
            model_name='resourcevoucherauth',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_authorizations', to='resource.resourcevoucher'),
        ),
        migrations.AddField(
            model_name='resourcevoucherauth',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='resourcevoucherauth',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='resourcevoucherauth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rbac.user'),
        ),
        migrations.AddConstraint(
            model_name='resourceauth',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__isnull', False), ('user__isnull', True)), models.Q(('role__isnull', True), ('user__isnull', False)), _connector='OR'), name='resourceauth_exactly_one_of_role_or_user'),
        ),
        migrations.AddConstraint(
            model_name='resourcevoucherauth',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__isnull', False), ('user__isnull', True)), models.Q(('role__isnull', True), ('user__isnull', False)), _connector='OR'), name='resourcevoucherauth_exactly_one_of_role_or_user'),
        ),
    ]
