# Generated by Django 5.2.2 on 2026-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcegroupauth',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
